---
- hosts: all
  become: yes
  tasks:
  - name: Get deb
    shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu18.04_all.deb
  - name: Add zabbix apt repo
    shell: sudo dpkg -i zabbix-release_6.0-4+ubuntu18.04_all.deb     
  - name: Update repo
    apt:
      update_cache: yes
      cache_valid_time: 3600      
  - name: Install zabbix-agent
    apt:
      name: ['zabbix-agent']
      state: latest  
  - name: Configure Server
    shell: sudo sed -i 's/^Server=127.0.0.1/Server={{zbxserver_ip}}/g' /etc/zabbix/zabbix_agentd.conf   
  - name: Configure ServerActive
    shell: sudo sed -i 's/^ServerActive=127.0.0.1/ServerActive={{zbxserver_ip}}/g' /etc/zabbix/zabbix_agentd.conf  
  - name: Configure Hostname
    shell: sudo sed -i 's/^Hostname=Zabbix server/Hostname={{ansible_hostname}}/g' /etc/zabbix/zabbix_agentd.conf        
  - name: Create script directory
    file:
      path: /etc/zabbix/scripts
      state: directory
      mode: '0755'
      owner: root
      group: root
  - name: Copy userparameter conf
    copy:
      src: userparameter_nvidia_k300.conf
      dest: /etc/zabbix/zabbix_agentd.d/userparameter_nvidia_k300.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy script file
    copy:
      src: get_gpus_info.sh
      dest: /etc/zabbix/scripts/get_gpus_info.sh
      owner: root
      group: root
      mode: '0755'        
    notify: Restart zbxagent
  handlers:
    - name: Restart zbxagent
      service:
        name: zabbix-agent
        state: restarted
