---
- hosts: all
  become: yes
  tasks:
  - name: Add elastic.co apt key
    shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - name: Add elastic.co apt repository
    shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list     
  - name: Update repo
    apt:
      update_cache: yes
      cache_valid_time: 3600      
  - name: Install filebeat
    apt:
      name: ['filebeat']
      state: latest
  - name: Configure filebeat defaults
    shell: sudo update-rc.d filebeat defaults 95 10
  - name: Configure syslog
    shell: sudo sed -i 's/*.log/syslog/g' /etc/filebeat/filebeat.yml
  - name: Configure elasticsearch ip to use when sending the data collected by the beat
    shell: sudo sed -i 's/localhost:9200/{{elasticsearch_ip}}:9200/g' /etc/filebeat/filebeat.yml   
  - name: Configure https
    shell: sudo sed -i 's/#protocol/protocol/g' /etc/filebeat/filebeat.yml
  - name: Configure username
    shell: sudo sed -i 's/#username/username/g' /etc/filebeat/filebeat.yml
  - name: Configure password
    shell: sudo sed -i 's/#password/password/g' /etc/filebeat/filebeat.yml
  - name: Configure password 2
    shell: sudo sed -i 's/changeme/CKKroot!/g' /etc/filebeat/filebeat.yml
  - name: Configure ca
    shell: sudo sed -i 's/#ssl.certificate_authorities/ssl.certificate_authorities/g' /etc/filebeat/filebeat.yml  
  - name: Configure ca 2
    shell: sudo sed -i 's/["/etc/pki/root/ca.pem"]/["/etc/filebeat/ca.crt"]/g' /etc/filebeat/filebeat.yml  
  - name: Change to true to enable filebeat input configuration
    shell: sudo sed -i 's/false/true/g' /etc/filebeat/filebeat.yml
    notify: Restart filebeat
  handlers:
    - name: Restart filebeat
      service:
        name: filebeat
        state: restarted
