---
- hosts: all
  become: yes
  tasks:
  - name: Copy hostgroup-create-tank-server.json
    template:
      src: hostgroup-create-tank-server.json.j2
      dest: /home/k300/hostgroup-create-tank-server.json
      owner: root
      group: root
      mode: '0644'
  - name: Add Host Group for Server
    ansible.builtin.uri:
      url: http://localhost/zabbix/api_jsonrpc.php
      #user: "admin"
      #password: "admin"
      #force_basic_auth: yes
      method: POST
      body_format: json 
      validate_certs: false
      src: /home/k300/hostgroup-create-tank-server.json
      remote_src: yes
  - name: Copy hostgroup-create-tank-switch.json
    template:
      src: hostgroup-create-tank-switch.json.j2
      dest: /home/k300/hostgroup-create-tank-switch.json
      owner: root
      group: root
      mode: '0644'
  - name: Add Host Group for Switch
    ansible.builtin.uri:
      url: http://localhost/zabbix/api_jsonrpc.php
      #user: "admin"
      #password: "admin"
      #force_basic_auth: yes
      method: POST
      body_format: json 
      validate_certs: false
      src: /home/k300/hostgroup-create-tank-switch.json
      remote_src: yes   
